### ISSUE TITLE
Main proc with all mandatory arguments results in compilation error.

### ISSUE THREAD

**Issue by yglukhov** [c-blake/cligen#1]
```nim
proc foobar(option: bool) =
   discard
import cligen
dispatch(foobar)
```
Error:

> .nimble/pkgs/cligen-0.5.0/cligen.nim(96, 34) Error: ambiguous call; both argcvt.argHelp(helpT: seq[array[0..3, string]], defVal: char, parNm: string, sh: string, parHelp: string): typed and argcvt.argHelp(helpT: seq[array[0..3, string]], defVal: bool, parNm: string, sh: string, parHelp: string): typed match for: (seq[array[0..3, string]], Error Type, string, string, string)

**Comment by yglukhov** [comment]
Hrm, can't see how its fixed. Still fails with my sample. Did you forget to commit anything? ;)

**Comment by c-blake** [comment]
Sorry - I could have sworn I saw cligen.nim in the file list.  The fix is there now.  To be clear, it was always supposed to fail (at least in the current cligen model), but the error message before was less helpful than the current one.

**Comment by yglukhov** [comment]
Ah, ok, thanks for clarification. Could I then request a feature to handle params with no defaults in runtime? E.g. don't dispatch, where some args are not passed?

**Comment by c-blake** [comment]
I'm not exactly sure what you mean for a runtime thing.  I could easily see (all at compile time) cligen generalizing its model mapping APIs <-> commands for non-defaulted parameters like "myproc(alpha:int, beta:float, opt1=2, opt2=4, rest: seq[string])" to map to a command like "mycmd --opt1=foo --opt2=bar {alpha} {beta} [rest...]".  `alpha` and `beta`  could even get converted with our argument converter/parsers but be non-optional.  There could also be multiple non-defaulted seq[]s as well (which on the command-line could be separated by "--").  I think there are some notes along these lines in my long README.md.  I can't work on this sort of generalization today, but perhaps soon.

**Comment by yglukhov** [comment]
Ok, let me put it in another way.
```nim
proc foobar(someArg1: int, someArg2: int, otherArgs: seq[string]) =
  # This function is never called if user doesn't provide --someArg1=someVal --someArg2=someVal in the CLI
   discard
import cligen
dispatch(foobar)
```
Running this tool:
```
$ foobar "hi"
Error: mandatory params missing.
< usage here >
```

**Comment by c-blake** [comment]
Ah.  I understand your idea now.  Well, the "ordinary/typical" command syntax/semantics is that `-` or `--` indicate always-optional named arguments that can occur in any position/order.  On the other hand, mandatory parameters are ordinarily/typically "position-sensitive".  So, I feel like my idea above (with the `{alpha}`) would produce CLI's closer to what command-line users expect.  Yours might be easier to implement and the help string could of course explain things.  Hmm.  Somewhere "in between" might be to have mandatory parameters be "dash-less" like `mycmd --opt1=5 alpha=1.23 beta=5 file1 file2`.  I could be wrong, but I suspect that either dash-less named parameters or mandatory positional parameters would be more popular ways to go rather than your "some dashed parameters being optional and others mandatory".

**Comment by yglukhov** [comment]
Ok, I think I'll have to agree. Then I'll be waiting for positional args thing :)

**Comment by c-blake** [comment]
Well, I added mandatory unnamed positional argument handling.  Seems to work ok for me in preliminary testing.
