### ISSUE TITLE
Can we specify custom doc strings for switches which then show up in the cligen generated help?

### ISSUE THREAD

**Issue by kaushalmodi** [c-blake/cligen#145]
Here's an idea:

```nim
proc revert(patterns: seq[string];
            force = false;                   ## custom doc string for --force switch
            ignoreFileExists = false;
            timeStampChangeIgnore = false) =
  ## Revert one or more files. By default, only unmodified files are
  ## reverted.
```

Current output is:

```
revert [optional-params] [patterns: string...]
Revert one or more files. By default, only unmodified files are reverted.
Options:
  -h, --help                                print this cligen-erated help
  --help-syntax                             advanced: prepend,plurals,..
  --version                    bool  false  print version
  -F, --force                  bool  false  set force
  -i, --ignoreFileExists       bool  false  set ignoreFileExists
  -T, --timeStampChangeIgnore  bool  false  set timeStampChangeIgnore
```

Expected:

```
revert [optional-params] [patterns: string...]
Revert one or more files. By default, only unmodified files are reverted.
Options:
  -h, --help                                print this cligen-erated help
  --help-syntax                             advanced: prepend,plurals,..
  --version                    bool  false  print version
  -F, --force                  bool  false  custom doc string for --force switch
  -i, --ignoreFileExists       bool  false  set ignoreFileExists
  -T, --timeStampChangeIgnore  bool  false  set timeStampChangeIgnore
```

**Comment by kaushalmodi** [comment]
Ah yes, I forgot about the `help` parameter in [`dispatch`](http://c-blake.github.io/cligen/cligen.html#dispatch.t%2C%2Cstring%2Cstring%2Ctyped%2Ctyped%2Cseq%5BT%5D%5Bstring%5D%2Cseq%5BT%5D%5Bstring%5D%2Cstring%2Cseq%5BT%5D%5Bstring%5D%2Cseq%5BT%5D%5BClAlias%5D%2Cseq%5BT%5D%5Bstring%5D).

**Comment by kaushalmodi** [comment]
I don't know if parsing the doc string from:

```nim
proc revert(patterns: seq[string];
            force = false;                   ## custom doc string for --force switch
```

If it is, I would love to have that feature.  :)

**Comment by c-blake** [comment]
We could apply that `hl`/`specifierHighlight` proc to `help[param]`.  That isn't done exactly right now - you can only control the highlighting of the whole of all of the `help[param]`s.  We might be able to parse for something really simple like `--nameWeKnow`. Something to think about.  I had been thinking of doing that for the `$doc` area already.

**Comment by c-blake** [comment]
If you wanted to work on a PR, I would say adding `specifierHighlight` calls before using `$doc` and `help[param]` or else in a preprocessing stage early would be about 10x easier than trying to parse stuff and give folks like you the ability to be precise in how they add bold/italic/*any* kind of text embellishment in those two areas.  That's more powerful  to the end user and less hard to code.  (I know how source code syntax highlighters work with regexes and all that...I just think they're often glitchy/approximate/etc. and that in this case you might *still* want the explicit stuff just to "***bold-italic*** my intent!"  So, if you have it anyway the natural text parsing seems to matter less since it's all documentation.  That's how Unix man pages work.  General font switching mechanisms and manual not automatic conventions.

**Comment by c-blake** [comment]
Our formatting language would simply be the wordier `%(bold italic)upToNextWhiteSpace` instead of `\fBIupToNextWhiteSpace\fR`, but people could also do a "bi" color alias and make that `%(bi)upToNextWhiteSpace` which isn't so bad.  And it might be more feature than bug to keep people down to one word or else repeat that %(bi) over and over to make them more keenly aware of how much they're shouting at a user. :-)

**Comment by c-blake** [comment]
We might need to not rely on the CL user to do a `bi` alias for us, though that isn't hard.

An entirely alternate idea long these lines would be an RST or Markdown to ASCII-with-escape highlighting system which occurred to me.  We'd want it o be NO_COLOR sensitive and probably want to use our own color schemes/themes/aliases, though, and I'd prefer not to have a mandatory new dependency.

**Comment by kaushalmodi** [comment]
I am confused. I am not referring to highlighting. I meant .. a feature to auto-extract the help strings for switches from the `## ..` comments to the right of those proc parameters, just as the sub command's help is extracted from the proc's doc string.

**Comment by c-blake** [comment]
Oh?  We are talking about very different things, then.  Sorry that I misunderstood.

What you are saying has been asked for/suggested before and there was a time when the Nim AST would contain some kind of structure for fields in object definitions like that, but it has long since passed.  Araq took it away.  TimotheeCour was asking for it.

For the proc area there was never any such.  We would have to kind of "guess" to "structure" things...binding particular parameters with particular `##` strings.  I'm not against it at all - in fact I'm quite "for it", but it also seems hard to possibly impossible.

**Comment by c-blake** [comment]
It now makes total sense to me why you just forgot about `help["myParam"]` and closed the issue on your own.  But I think there remain interesting ideas in my response. :-)

**Comment by c-blake** [comment]
Anyway, I even tried to figure it out at the very, very beginning but decided on `help[param]` instead.  2nd thing in README.md.  It would absolutely be  better "dual API-CLI" documentation system and JavaDoc and others work that way.

**Comment by kaushalmodi** [comment]
>  2nd thing in README.md

Sorry, in hurry I was searching for "doc" in the cligen API docs. But then I rediscovered the help parameter. 

This is regarding that same p4x project. I have dozens of switches to document. And scrolling up to the procs above and then to the dispatch call at the bottom to type the doc strings is not convenient. 

I'll keep on thinking if there's any way to improve that given what nim ast allows. 

Thanks.

**Comment by c-blake** [comment]
This is the prior discussion: https://github.com/c-blake/cligen/issues/30

The problem is that, without some rigid, this-is-how-you-gotta-do-it "comment subsyntax" like JavaDoc *or* any particular "community trend" roughly to that effect, there will be a lot of things like this in the wild:
```Nim
proc(a, b: int;  ## a means this; maybe I don't say anything about b
     c, d: float) =  ## d means this; maybe I say nothing about c.
  ## main doc body
  discard
```
or maybe lines with no comment at all, etc.  It becomes an almost "AI-complete" (after NP-complete - solving any problem in the class is all as much as human generalized intelligence) thing.  It's worse, really.  One human could easily confuse another to the point where we'd have no idea.  So, at best we would always need those `help[param]` overrides.

At worst, after mountains of work, our auto-defaults would still suck and everyone would just use `help[]` anyway...or, alternatively they'd be annoyed at us for indirectly imposing doc-formatting conventions they don't like that makes their code seem overly bureaucratic and worse probably bleeds into *all* API calls, not merely those that get a `cligen` wrapper.
