### ISSUE TITLE
Can't supress --help-syntax option

### ISSUE THREAD

**Issue by halloleo** [c-blake/cligen#175]
I try to suppress the `--help-syntax` option, so I added `{"--help-syntax": "SUPPRESS"}` to the help dictionary, but cligen complains because `--help-syntax` is not an _API_ option.

How can I suppress `--help-syntax`?

**Comment by c-blake** [comment]
As per https://github.com/c-blake/cligen/commit/43f80c2fdfddf1d2fb4794b00ae72ccca58c60b0, somewhere after import cligen and before your dispatch just do:
```Nim
clCfg.helpSyntax = ""
```
This won't make `mycmd --help-syntax` illegal, but will suppress it in the help table.  For non-internal options you can follow `tests/OmitInHelpTable.nim`.

I personally think suppressing syntax help is a little user-hostile since `cligen` expands otherwise typical syntax quite a bit, but to each his own.

**Comment by halloleo** [comment]
Thanks for this. You are _very_ helpful, @c-blake.

Works as advertised - and is certainly good enough for me. :smile: 

One question though: Where does the `helpSyntax` field come from. In [ClCfg description](http://c-blake.github.io/cligen) I cannot find.

**Comment by halloleo** [comment]
Ups, sorry, my bad. I just saw that in the [source code](https://github.com/c-blake/cligen/blob/master/cligen.nim) the `helpSyntax` field is listed.
