### ISSUE TITLE
`strUt` requires Nim 1.2+

### ISSUE THREAD

**Issue by SirNickolas** [c-blake/cligen#226]
`cligen/strUt` fails to compile on Nim <=1.0 because of mixed arithmetics between `uint64` and `int` literals, usage of undeclared `csize_t`, and perhaps something else. This doesn’t cause me any troubles, but I thought you had to know.

**Comment by c-blake** [comment]
Yes.  Thanks for the report.

I was aware that helper library code outside the main `test/` suite is more sensitive to Nim version.  But the main test/ suite works on even Nim-0.20.2.  There is no real way to specify this, and it is not a frequent thing in open source, but there remains value to not raising the bar on Nim version in `cligen.nimble`.  Most `cligen` client code *only* uses the core functionality, not "satellite functions". Meanwhile, keeping all the satellite stuff working back to 0.20.2 takes work.  What I will do to resolve this issue is put a big ALL-CAPS comment in `cligen.nimble` near the version specification.
