### ISSUE TITLE
[low priority] automated generation bash/zsh completion and man page generation

### ISSUE THREAD

**Issue by timotheecour** [c-blake/cligen#23]
this would be a cool thing to have (but not as urgent as other issues)
in theory there's all we need to automatically generate man pages and bash/zsh completion

./app --generate_bash_completion=output_file
./app --generate_manpage=output_file

**Comment by c-blake** [comment]
Well, Zsh already has ``compdef _gnu_generic myCommand`` that will parse output of ``myCommand --help`` and use that for autocompletions.  I actually use this all the time for my cligen-generated commands.  So, I know it works.  They presence of extra type info (``string``, ``int``, etc.)  doesn't confuse their parser at all.

I am 95% sure bash has something similar.  So, this is really already there.

Man pages are another story, but I also don't think cligen is the place for that functionality.  I think a package/program that took ``myCommand --help`` and turned it into a proto-man page from a template would be more useful.  It would work for commands not written in Nim or not with cligen, etc.  I would probably use/promote such a tool if it was good, but I think for cligen I should close this issue.

**Comment by timotheecour** [comment]
wow thanks, didn't know!

**Comment by timotheecour** [comment]
@c-blake 

this is cool:

```
ompdef _gnu_generic nim # nim --adv #autocompletes

brew install help2man
help2man nim -o /tmp/man
man /tmp/man #works!
``

I think it's worth mentioning `ompdef _gnu_generic` and `help2man` in README since users of cligen are very likely interesed in completion and man pages. I don't think

**Comment by c-blake** [comment]
I do not think `_gnu_generic` itself claims to support subcommands.  The problem here is that the way `_gnu_generic` works is to parse output of `cmd --help`.  While for a single command there is "almost always" a "sort of/kind of table", there is drastically less standardization of the output of help for multi-commands/commands with subcommands.

I think a `_multi_generic` would be very useful, but it might need to be "more or less" cligen-specific.  I would also be happy to include such in the `cligen` distribution/repository.
