### ISSUE TITLE
Build error with nim 2.2.0

### ISSUE THREAD

**Issue by YamatoSecurity** [c-blake/cligen#234]
I am getting a build error with 2.2.0. (v2.0 works fine)
```
/Users/xxx/.nimble/pkgs2/cligen-1.6.13-3ea97209d5fd4f21adb419efbc269bbc2afcbd30/cligen.nim(659, 22) template/generic instantiation of `argParse` from here
/Users/xxx/.nimble/pkgs2/cligen-1.6.13-3ea97209d5fd4f21adb419efbc269bbc2afcbd30/cligen/argcvt.nim(171, 27) Error: type mismatch
Expression: doArgParse[BiggestInt](parseBiggestInt, dst, dfl, a)
  [1] parseBiggestInt: proc (s: string): BiggestInt{.noSideEffect, gcsafe.} | proc (s: openArray[char], number: var BiggestInt): int{.raises: [ValueError], noSideEffect, gcsafe.} | proc (s: string, number: var BiggestInt, start: int): int{.raises: [ValueError], noSideEffect, gcsafe.}
  [2] dst: var int
  [3] dfl: int
  [4] a: var ArgcvtParams

Expected one of (first mismatch at [position]):
[2] template doArgParse[WideT: SomeNumber; T: SomeNumber](parse: untyped;
    dst: var T; dfl: T; a: var ArgcvtParams): bool
  missing generic parameter: T

       Tip: 65 messages have been suppressed, use --verbose to show them.
nimble.nim(304)          buildFromDir

    Error:  Build failed for the package: takajo
```

Project: https://github.com/Yamato-Security/takajo

By the way, I was able to install 1.7.6 with `nimble install cligen`, however, when I run `nimble update` and `nimble upgrade`, the version gets stuck at `1.6.13` for some reason.

**Comment by YamatoSecurity** [comment]
We were able to finally get it working with 1.7.6 and is working now.

**Comment by c-blake** [comment]
Yeah.  Sorry.  This was an old sorta-bug that only became detected by newer compilers.  As per the [RELEASE_NOTES.md](https://github.com/c-blake/cligen/blob/master/RELEASE-NOTES.md) for version 1.7.4 this was fixed by 60476dd4804422ca377efea6544a9ea7033a2f93 .

I don't really use `nimble` myself and never ever ever use update/upgrade.  To the extent I test installs into empty `nimble` repos with it, I try to use [`nrel -u`](https://github.com/c-blake/bu/blob/main/doc/nrel.md) and specific latest version numbers to make `nimble` get most recent versions.

If you can reproduce your update/upgrade problem then you may have a good [`nimble`](https://github.com/nim-lang/nimble) bug to report (if it is not already an open issue).  (I realize this may depend on details of filetree state, but then you may also have backups/whatever.)

**Comment by c-blake** [comment]
One thing I noticed that may be relevant is that your `takajo.nimble` file does not end with a newline or carriage-return-newline pair (i.e. after `db_connector`).  While it's possible that messes up something, it seems more likely a problem elsewhere, but I thought I should mention it.

**Comment by YamatoSecurity** [comment]
@c-blake Thanks for the information! I'll try adding a carriage return at the end and hopefully that fixes something. Indeed, it looks like a nimble bug.
