### ISSUE TITLE
nested help for dispatchMulti: analog to `git help remote`

### ISSUE THREAD

**Issue by timotheecour** [c-blake/cligen#24]
```
./app --help #same as before
./app --help=proc1 # only shows (autogenerated) help for proc1 (also: --help proc1, --help:proc1)

# alternative syntax (analog to `git help remote`)
./app help proc2 # only shows help for proc2
```

## related
* somewhat related to https://github.com/c-blake/cligen/issues/22 but that issue deals with deeper nesting; my issue deals with nesting of (auto-generated) help:

* from readme:
> ./cmd --help will emit a brief help message and ./cmd help emits a more comprehensive message.

not same as I'm suggesting here

**Comment by c-blake** [comment]
I don't know.  Currently, ``app -h`` gives a little info and tells the user what to do to get more, and ``app help`` gives a full dump.  If you want help for just one subcommand you can say ``app sub --help`` which seems _at least_ as intuitive as ``app --help=sub``.  (and ``app -h`` tells the user my syntax for it, too.)  There aren't that many of these multi-commands around to really say there's a standard way of doing things.

As a user, I could see making the full dump more brief like just a list of subcommand names and require a ``-v`` or something for full help, but it was really _much_ easier to code the way it is currently.  Even trying to add ``-v`` to get full help is a pain, though.  I let users change the name of the subcommand within their individual dispatch settings if they want with ``cmdName``.  So, I'd have to parse all the brackets looking for any of those (which could be anywhere since the named parameters let order not matter).  In short, I think I would only really like ``help -v`` or ``help -a`` here, not your idea, but I'm not sure the payoff is worth the work.  A lot of people just want to see the whole help, not jump through hoops.

**Comment by timotheecour** [comment]
> If you want help for just one subcommand you can say app sub --help which seems at least as intuitive as app --help=sub

I agree with you, `app sub --help` is better; I just didn't know it was supported (didn't find it in README)

> app -h gives a little info and tells the user what to do to get more, and app help gives a full dump
> In short, I think I would only really like help -v or help -a here, not your idea

Instead of making -h different from --help (which would be an exception to usual rule), how about the following instead: allow string argument to --help/-h

eg: 
```
--help
--help=full
# if later we want to extend it:
--help=color:false,full:true,man:true
```

that way, it works with same logic regardless whether --help is used with dispatchMulti or dispatch

**Comment by c-blake** [comment]
Yeah...Maybe when NoVal becomes OptionallyNoVal interpreting the optional value to ``help/h`` would be a clean way to go..It could print the whole help with options table by default or a briefer just command name & doc comment and the ``dispatchMulti`` could just call it with the brief mode for the ``help`` subcommand and the full mode for ``help -v``.  That's really easy to do in this future NotNecessarillyVal world that is a bit of work to realize.

Doc-wise, the main ``app -h`` help message mentions ``app subcmd --help``.  If you had compiled & run a test you would have seen it.  Or looked in the test/FullyAutoMulti.nim section of test/ref.   That (and surely other things, like FancyRepeats style stuff) could use better documentation.  All I really have is the README.md and it's gotten kind of long.  I should probably split that up into a high level pitch and then a more thorough document.

**Comment by timotheecour** [comment]
my 2 cents: to avoid making the README a giant wall of text, it'd be helpful to have in README a full fledged example showcasing all/most options; would make it easy to digest for users. eg:
```
proc fun(different types of args):auto = ...
dispatch(fun, put all/most args)
dispatchMulti(...)
./app -h # or --help
./app -v:false -glh --foo:true -w=0 --baz+=mypath -x=1,2,3
./appmulti sub --abc=foo 0
./appmulti sub --help # print top-level help
./appmulti sub --help=full # print help recursively
```

**Comment by c-blake** [comment]
The question is also always "which document/section is for whom?"  Your example is more full-fledged use by the CLI user.  I wrote the README for CLI authors contemplating a low-effort CLI making tool, presuming that if their interest is really piqued they would at least read the rest of the README and some example code in ``test/`` and run some test programs.  I should probably direct people to the test programs and maybe make a table of what they test a bit more descriptive than their filenames.  There should be more example code, too.
