### ISSUE TITLE
feature: allow passing as nim arguments`--nimargs='32.0, foo: 2, bar:"hi", x=@[1,2]'`

### ISSUE THREAD

**Issue by timotheecour** [c-blake/cligen#25]
I had actually implemented something like that in D, I think it would make a lot of sense for cligen.

the Idea is to have as an option a way to call your nim function from cmd line in the same way as you'd call from nim, eg:

```
void fun(a: double, foo: int, bar: string, x: seq[int]):auto=...
./app --nimargs='32.0, foo: 2, bar:"hi", x=@[1,2]'
#same as
./app --a=32.0 --foo=2 --bar:hi ...
```
this makes it easy to interchangeably call your program either from cmd line or from nim / inim

**Comment by c-blake** [comment]
Unlike D, Nim already has pass-by-name calling.
Nim: ``app a=32.0 foo=2 bar="hi" x=@[1,2]``
Zsh: ``app --a=32.0 --foo=2 --bar=hi --x=1,2``

That's actually just a concrete example of what I mean abstractly by my very second sentence in README.md, and partly why I think something like cligen can be a good idea.

Invokers using both access paths do have to understand/remember the mapping, but things can never be identical.  In your proposal the CLI user has to quote all that Nim, e.g., embedded single-quotes for ``char`` literals, and the Nim user can use the entire Nim expression syntax for the RHS of '='.  Even if CLI users had a run-time Nim evaluator for the whole RHS (which may well be infeasible in general deployments of Nim and the generated command), that Nim RHS would also still need quoting..shell metacharacters in "", etc.  I.e., even if you dumped the string into a file to run the compiler on you need the compiler around which makes the command have a rather severe runtime dependency deploying command -- Nim and C compiler availability and all the configs and PATHs right.  Also, an ambitious CLI author can fiddle with the mapping quite a bit including changing ``app``.  Also since micro-DSLs for parameter values from such fiddling provide a way to be easier on CLI user, this source of CLI-API variation is actively desired.

So, I think I'm going to have to say that I disagree that this would make a lot of sense for cligen.

**Comment by c-blake** [comment]
Another way in which things are different in the two domains and should probably stay that way is that the keywords are optional in the Nim calls..Depending on the order of received parameters in the ``proc``, ``app(32.0, 2, "hi", @[1,2])`` could also work.  Even if it is "do-able" (the way I presently do mandatory parameters), that sort of flexibility is even more unusual/non-standard in the CLI world than toggles are.  This "either order or keyed" approach to get closer API/CLI correspondence in some "cut & paste" sense would lead to longer/weirder usage/help messages..Possibly so long/weird that only Nim programmers might "get it" without a lot of hand holding.  I think keeping the correspondence "pretty close" within the two respective "invocation domains" and making it easy for CLI authors to code up some custom ``argParse/Help``s is the right level of complexity to target.

Another set of ideas vaguely along these lines which I have thought a little about (but not coded anything up for) is inferring/generating other kinds of UI -- very web forms and GUIs in particular.  The UIs in those domains would be _very_ minimal compared to same-domain competition, but might be "more supported" for geeky functionality usually requiring APIs. ``dispatchMulti`` type work would probably be the most common..The web form case is easier.  Say insert several forms (one per dispatch) into some HTML template and have Nim write out the filled in template as part of also compiling the CGI to handle it.  There's probably quite a bit more "output translation" there - many outputs cannot just go to the stdout or files or whatever the same as in a proc invoke vs. cmdline invoke duality.  Some long-lived GUI with many "one-shot" kinds of dispatch is also possible.  Each member of a ``dispatchMulti`` could be a menu pick to get to an data entry page with sliders for floats and ints and boxes for strings and maybe some nice enum->radio box, etc. with a submit with output translating being even more involved.  (Obviously people do things that fancy in HTML, too.  I don't mean these to be exclusive ideas, but web forms have more of an intrinsic fire-and-done dispatch pattern like a proc call).  One other issue here is that while command-line users almost invariably have at least a bit of a "programmer's mindset", web form/GUI users are a whole different ballgame, as the saying goes.

Anyway, I'm not very motivated to engage with those large other UI generation projects.  I'm a command-line guy, myself, as it seems you probably are (it seems highly correlated to being a Zsh user).  I didn't like the stiff ``parseopt`` syntax, knew of ``argh``, saw the potential, and wrote cligen for myself/my own Nim command projects at home.  It came out nice enough to use that I thought it worth sharing.

I'd say that having a generic argParse/argHelp for any Nim ``object`` would be a great addition..It's probably just some simple embedded in one string DSL for initializing all the fields/nested fields.  That kind of thing is currently probably the biggest pain point of API/CLI correspondence.  See https://github.com/c-blake/cligen/issues/2  where I think they want a "flattened" one - use the whole command-line breaking the "one string corresponds to one Nim parameter" correspondence. I think that is a "new arc"similar to the UI ideas above but in a different direction.
