### ISSUE TITLE
option to dispatch from object's fields => leads to better API's and more DRY code

### ISSUE THREAD

**Issue by timotheecour** [c-blake/cligen#30]
currently code using cligen is not as DRY as it could be, eg:
```nim
type App = ref object
    nim: string
    srcFile: string
    showHeader: bool
    other: string

proc main(nim="nim", srcFile = "", showHeader = true, other = nil) =
    app.new()
    app.nim=nim
    app.srcFile=srcFile
    app.showHeader=showHeader
    if other == nil:
      app.other = nim & " FOOBAR"
    else:
      app.other=other
   
   # rest of code...
   echo app.repr

when isMainModule:
    import cligen
    dispatch(main, help = {
            "nim": "compiler to use",
            "srcFile": "script to run",
            "showHeader": "show informative compiler info",
             "other": "defaults to smthg inferred from other args",
        })
```

I'd like to be able to write instead the following, while keeping the same generated cmd line:
```nim
type App = ref object
  nim: string ## compiler to use
  srcFile: string ## script to run
  # non-doc comment: this won't appear in `help`
  showHeader: bool ## show informative compiler info
  other: string ## defaults to smthg inferred from other args

proc newApp(): auto=
  result = App(nim:"foo", srcFile:"bar", showHeader: false)
  result.other = result.nim & " FOOBAR"
  
proc main(app = newApp()) =
  echo app.repr

when isMainModule:
  import cligen
  dispatch(main) # help inferred from fields' documentation comments
```

advantages:
* the documentation is where it should be, in the field definition (also, nim doc could see those I believe); NOTE: only documentation comments would be exposed in help
* with lots of fields, passing args through an object is cleaner than passing each field individually (similar rationale as https://github.com/citycide/glob/commit/3fbdb188750e98f305983662202d6993d3d1a893) 
especially when `main` needs to be called as a library from another function: better to pass a single object/ref object than pass each field individually (ie, encapsulation)

NOTE:
* feature should work with either object or ref object

**Comment by c-blake** [comment]
Did you read through https://github.com/c-blake/cligen/issues/2 ?  I see your point about repetition of parameter help strings, though.

There are definitely namespace issues which would limit this/require more thought.  ``main()`` could easily take two or more arguments with type fields that had the same Nim identifier (like some generic "name").  Then some whole mechanism would also be needed to map these to the CLI with probably CLI author overrides, etc.

I wonder if it is possible/easy to just export some new a helper proc ``helpFromType`` so my last code example in that https://github.com/c-blake/cligen/issues/2 thread could instead read:
```Nim
dispatchGen(init, cmdName="whatever", help = helpFromType(App))
```

**Comment by timotheecour** [comment]
Indeed related to #2. 

You're right that we can pass `newApp` (the proc generating defaults) + `cmdName` instead of passing the consuming proc `main` to `dispatch`:
~~`dispatch(main)`~~ vs `dispatchGen(newApp, cmdName="whatever")`

dispatchGen is probably better, avoids ambiguities in case `main` is overloaded (let's just not consider case of `newApp` being overloaded).

That being said, instead of the complications you mention in https://github.com/c-blake/cligen/issues/2#issuecomment-390494556 how about the following which is much simpler:

`dispatchGen(App, defaults = newApp(), cmdName="whatever")`

that way, we get everything needed including:
* the default values explicitly via `defaults` param (we don't care how user generates this, avoiding all complications you mentioned)
* the help for each field from the type by parsing the AST given the type (`helpFromType(App)`)

Anything missing?

**Comment by c-blake** [comment]
From your invocation example, it looks like you want to pass a Nim type rather than a ``proc`` as the first argument to ``dispatchGen`` and treat the just-first-level of the type as the (name, expression) mapping.  So, that's a whole new overload for ``dispatchGen`` and kind of a lot of work -- if overloading on macros even works.  We could take more untyped things and try to inspect type-hood vs. proc-hood and switch off that, too.  We could always pick another name, too, and look into lifting common code.  In this case it would look like ``dispatchGenFromType[T](T, defaults: T, ..)`` or maybe something with more ``untyped`` aspects.

Beyond the minor syntactic aspects and possibly cut & paste code explosion, it's important to note that you could only really do one level automagically.  Fields/members with complex/compound types would still need their own parse/help stuff.  There's a real risk of people asking for recursive completeness here, but automatically flattening a hierarchy is fundamentally heuristic.

In terms of code explosion, besides proc parameters and type definitions, people may also just have some unbundled set of global variables which I believe also
get '##' doc-comment nodes.  That would be yet a third source of names which might come bundled with defaults and help strings.

So, if we're going to do this, it would probably be best to have some generic layer that we could invoke from all three sources.

In the end, it seemed to me that this is exactly what an init proc is - a mapping from names to expressions with types to boot and full support already in the Nim AST.  The only gotcha is help string ancillary data, but that is part of the
niceness of ``cligen``, too.

I'm open to working on a pull request with you, but I'm not sure this proposal is "fully formed"/concrete enough in terms of the ``cligen``-internal coding.

**Comment by timotheecour** [comment]
@c-blake just sent out https://github.com/nim-lang/Nim/issues/8516 ; it may be required for at least the part that deals with extracting documentation comments; the rest could still work without that issue fixed though (and still provide DRY benefits and cleaner API's)

**Comment by c-blake** [comment]
Another thing that _might_ possible right now but not done is at least defaulting help strings to per-parameter doc comments in proc definitions, like:
```Nim
proc foo(a: int=1, ## alpha counter,
         b=2.0, ## beta frobniculator
         c="hochimamma") ## exclamation
```
It would almost surely require an extra-syntactic formatting assumption to translate those to bindings, and I'm not sure of the tree depth/how easy it is to pick that apart.  A lot of Nim code I've seen just stacks the parameters all together or in bundles and associated comments explaining parameters (if there even are any) would require a lot of natural language smarts to tease apart which aspects of the maybe comment went with which parameter.

That also raises another part of my impulse to punt on this aspect of DRY-ness...Explaining a parameter (whose name does not speak for itself in the context of the operation) to a command-user is different sort of natural language context than explaining a field or parameter to a programmer.  I get that better defaults are good and all that, but if the _best_ value will usually be something different from the default there isn't a great return on investment to spend a lot of time/effort at generating the better default.

**Comment by timotheecour** [comment]
we definitely shouldn't do any NLP smarts to tease these apart :)
however passing verbatim top-level `proc` comment to cligen is good for that case:

```nim
proc foo(age = 10, name = "hochimamma"): auto=
## ``foo`` computes a record give a user ``name`` and his ``age`` 
```

generates:
```
Usage:
  foo [optional-params] [paths]
``foo`` computes a record give a user ``name`` and his ``age`` 

Options (opt&arg sep by :,=,spc):
  -h, --help                  print this help message
  -a=, --age=  int     1      set age
  -n=, --name=  string   "hochimamma"    set name
```

**Comment by c-blake** [comment]
Sure, sure. There are easy workarounds if you know cligen's limitations.  The API author might just not care to make cligen's job easy or even know about the CLI.  When I began using the Python argh I was in that exact situation.  So, they may take pairs or triples of args with doc comments as "fine" but it would be inscrutable to cligen.  It would also probably be difficult for any other tooling/doc generation, though.

**Comment by arnetheduck** [comment]
I'd like use a feature like this to fill the config object from multiple sources: config files, env variables, command line options etc.

**Comment by c-blake** [comment]
I don't know how much of that would work, realistically.  cligen is currently a fully compile-time operation using regular old `case of` with string-literals.  Conf files that could be `staticRead` at compile time might work, but beyond that it's a major extension of its mode of operation and would require almost a total re-write.  In particular, type inference that is relied upon would have to be recreated or not relied upon which might spill over into not using Nim's overloaded dispatch, etc.

**Comment by arnetheduck** [comment]
I meant that the values in the object would be read from these multiple sources - just like the values of the config options come from the command line (dynamically) presently.

**Comment by c-blake** [comment]
Ah.  Well, this seems slightly off topic from this issue thread about other static sources from which to construct a parser. If you want other dynamic sources of data then you can just separate the `dispatchGen(foo)` invocation from calling the actual `dispatchFoo(cmdline=...)` and give whatever `cmdline` you want.  You could parse a config file into one `seq[string]`, env var(s) into another, and `let mergedCmd = fromConf & fromEnv &  commandLineParams(); dispatchFoo(cmdline=mergedCmd)`.  I also provide an `argPre` and `argPost` for env vars, but I never use those myself.  So, that could be buggy.  Passing a different `cmdline` should work, though.  I do that internally.

**Comment by c-blake** [comment]
Oops..`quit(dispatchFoo(..))`, but you get the idea.  And, of course, if you wanted to generate a parser for a config file from an object definition, not just effectively populate a command-line then this is on topic, but also quite a bit of an extension (file handling, tokenization, quoting, etc.).

**Comment by timotheecour** [comment]
@arnetheduck indeed, seems like an orthogonal issue; maybe create a new one and paste in the previous few posts there, makes it easier to follow

**Comment by c-blake** [comment]
For what it's worth, the more both https://github.com/c-blake/cligen/issues/13 and this issue sit in the unresolved column, the more I think they are _almost_ the same issue.  They at least share the same underlying hierarchy mapping problem in slightly different ways.  https://github.com/c-blake/cligen/issues/13 is a little simpler in that the CLI author is creating the hierarchy for presentation to a CLI user while this one is more about re-using a hiearchy possibly intended for API users/programmers for the CLI.

The two issues intersect in the situation where the CLI author purposefully creates an object type for their CLI.  Assuming giant-tree-CLI authors like @xmonader are willing to create a type for their CLI use which seems at least a "not totally crazy" assumption, they could use a `dispatchGenFromType` or maybe `dispatchGenFromTree` to do so and `dispatchMulti` could stay simple.  "Leaves" of both sorts of trees could probably just internally generate a proc and invoke `dispatchGen`.

Anyway, as I've said before on both issues, I'm happy to work on a PR with someone if they want to try, but I would not be surprised if there were bothersome Nim limits along the path.

**Comment by c-blake** [comment]
Well, it's been a few months since I've heard from you, but assuming you are still interested in Nim and/or cligen, I think the cleanest approach for this issue may be a layering where one writes a new entity (macro or module) called something like `initGen` that generates a `proc` which initializes some `var obj` from a named parameter list.

Then one can just call `var obj: MyType; initGen(obj, MyType, ...); dispatch(initMyType)`.  (Might be able to get `MyType` out of `obj` automagically in `initGen`). `initGen` itself could perhaps push off hierarchy problems onto the initGenner/CLI author in a way analogous to `./test/MultMultMult` does for deep hierarchies.  Might not be so bad if the common case was a shallow hiearchy/simple structure.  Might need a separate `fieldHelp` thing to be able to go `dispatch(initMyType, help=fieldHelp(obj)`.  

Once you got all that working it's probably not hard to wrap it up in an omnibus macro call like `var obj: MyType; initObjFromCL(obj)`.

**Comment by c-blake** [comment]
To make the above more concrete, what I mean is, e.g.:
```Nim
type App = ref object
  nim: string ## compiler to use
  srcFile: string ## script to run
  # non-doc comment: this won't appear in `help`
  showHeader: bool ## show informative compiler info
  synth: string ## synthetic inferred from other args

const dfl* = App()  #Nim defaults here, but can be whatever

var app* = dfl      #initFromCL targets instance app, not Type App.

proc appLogic*(): int =             #Down to here is likely needed..
  app.synth = app.nim & " FOOBAR"   #..for ANY app, not just a CLI.
  echo repr(app)

when isMainModule:
  import cligen     #In simpler cases, initFromCL(app) is enough
  initFromCL(app, suppress = @["synth"])  #All dispatchGen kwargs accepted
  appLogic()        #"CL-only" logic can be in-line here, of course
```
where `initFromCL` above expands to:
```Nim
initGen(app, suppress = @["synth"])
dispatchGen(initApp, suppress = @["synth", "o"],
             help=fieldDocs(App, suppress = @["synth"]))
try: dispatchInitApp()               #init o from CL
except HelpOnly,VersionOnly: quit(0) #exit on CL-user request
except ParseError: quit(1)           #or on CL-user error
```
where `initGen` generates `initApp(ob: var App=app, nim:string,..)`, and `fieldDocs` generates a `{}` table constructor.

`fieldDocs` needs the `suppress` to avoid no matching `help` key errors. There could be a non-exiting mode that instead sets some `addr clStatus` parameter.

`initGen` might optionally|instead produce `initApp(nim:string,..)` without the initial `var App` slot, i.e. `=initApp(result,nim,..)`.  These init procs might be useful in other contexts as an alternate syntax to `App(nim: x,..)`.  The ob-less form would also make `suppress` just pass through unaltered to `dispatchGen` which may be nicer.  Since it can be hard to indicate specific overloads, AFAIK, we'll let users override `initApp` to whatever to avoid collisions if they define some other in scope `initApp`.

UFCS does make it tricky to assign to a field with a name identical to a proc formal parameter, and we want the identical name both for CLI clarity and so there needn't be any weird munging keys/names in the constructor produced by `fieldDocs`.  So, we probably need to generate local `param1=` procs in `initGen` unless there's some other workaround I don't know about.

This design somewhat separates cmd-line concerns from how potential hierarchy inside `app` is given a flat name space in `initApp`.  init params simply need to agree with the keys `fieldDocs` forms, but `initApp` could be written manually.  If there are name collisions of fields, `fieldDocs` will need to do something, though.  Initially, it could just error out as a documented limitation.

Personally, without a working `fieldDocs`, I think this all has very limited value as the CLI author must replicate all the documentation for the object fields in the CLI help.  A reasonable starting point should just be manual `initApp` & getting `fieldDocs` working (as well as it can given whatever Nim core is thinking about comment fields in the AST).

**Comment by c-blake** [comment]
This basically works except for not looping over the fields in the 3 places `nimId` is used:
```Nim
type App = object
  nim: string ## compiler to use
  srcFile: string ## script to run
  # non-doc comment: this won't appear in `help`
  showHeader: bool ## show informative compiler info
  synth: string ## synthetic inferred from other args

const dfl* = App(nim: "nimcc")

import macros, cligen

macro initGen(T, df): auto =
  result = newStmtList()
  let initId = ident("init" & $T)
  let nimId = ident("nim")
  result.add(quote do:
    proc `initId`(`nimId`=`df`.`nimId`): `T` =
      result.`nimId` = `nimId`)

initGen(App, dfl)
dispatchGen(initApp)
try:
  var app = dispatchInitApp()         #init app from CL
  echo "app.nim is ", app.nim #app.synth = app.nim & " FOOBAR"
  #..or also maybe just app.logic()
except HelpOnly,VersionOnly: quit(0)  #exit on CL-user request
except ParseError: quit(1)
```
This `initGen` is really entirely exogenous to `cligen` machinery and could even be its own nimble package.

**Comment by c-blake** [comment]
And, of course, we could have `initGen` also emit an `initFromCL` (or maybe `initAppFromCL`) so that doing the `try`/assignment/`except`'s so that this usage would work:
```Nim
initGen(App, dfl)
var app = initFromCL()
app.logic()
```

**Comment by c-blake** [comment]
Closed by https://github.com/c-blake/cligen/commit/07e0f319adf13ce3eca3b69b0acf6d0e63de5812
