### ISSUE TITLE
[TODO] suggestions

### ISSUE THREAD

**Issue by timotheecour** [c-blake/cligen#43]
- [ ] use object instead of tons of params for dispatch, dispatchGen

would make code more readable, reusable, and more DRY

- [ ] separate out long string constant into a const string
also, it's a bit cleaner to separate out `"${prelude}$command $args\n$doc  Options(opt-arg sep :|=|spc):\n$options$sep",` as a separate const instead of inlining this string:
```nim
const usage = ""${prelude}$command $args\n$doc  Options(opt-arg sep :|=|spc):\n$options$sep"
```

- [ ] instead of:
```
echo "Usage:  This is a multiple-dispatch cmd.  Usage is like"
        echo "  $1 subcommand [subcommand-opts & args]" % [ `srcBase` ]
        echo "where subcommand syntaxes are as follows:\n"
```
use a single echo + fmt
```
echo fmt"...{srcBase} ... "
```

- [ ] likewise with 
```
"${prelude}$command {subcommand}\nwhere {subcommand} is one of:\n  " &
      join(`subcmdsId`, " ") & "\n" &
      "Run top-level cmd with the subcmd ...
```

**Comment by c-blake** [comment]
Yeah...I think about that every time I add something, but the reality for me and my commands is that I never use more than two or three named parameters, and also that this would also be a very backward incompatible change.

I suppose we could add just one more parameter that was an object which, if given, in effect changed all the parameter defaults and then tried to apply any *additional* tweaks people give on top of those defaults via other named parameters.  That would both satisfy your need, but also preserve backward compatibility and what I consider the more common use cases for less picky CLI authors.   PR welcome if you want to work on it.

**Comment by c-blake** [comment]
(P.S.: it would especially make sense/be helpful in a `dispatchMulti` setting.)

**Comment by c-blake** [comment]
Well, I updated some of that string constant stuff a little.  While I understand `fmt"..{var}.."` is a bit nicer, I could not get it to work in a macro context with the quasi-quoting `quote do: backticks`.  I don't personally consider it _that_ much nicer to bend over backwards about.  You might want to try out compiling some suggestions before firing them off.  While I do really like Nim's feature set/syntax, there are also a _lot_ of rough edges.

The only thing left in your suggestions list of substance, I think, is the object idea.

Another way that idea would help and/or be an argument for going whole hog and ditching the long param list and backward compatibility is that currently I have to capture arguments/parameters to `dispatchGen` in shadow locals in many places.  That's really annoying to me.  A lot of places the parameters to `dispatchGen` require a little massaging anyway, but some places they do not and I made pretty lame alternative names.  My personal inclination would have been to _-prefix or suffix them all, but Nim idents are insensitive to '_' and case flips past the first character.  So, e.g. `prelude` becomes `prlude` and junk like that.  Anyway, I didn't really chose a clear standard convention.  (Were I to psychoanalyze myself there, I was probably rebelling against ident style-insensitivity a bit.)  I _might_ be able to use `strVal` or API calls instead of `quote do:` a bunch of places, too, but that's about as annoying as all the name duplication.  I have a bunch of XXX comments in the code about that.

**Comment by c-blake** [comment]
Python has a nice way to package up and pass around keyword arguments with `**`.  I think if there is a lot of repetition of named parameters for picky CLI authors we should figure out how to do that in Nim.  I'm not at all sure that's possible given staticness vs dynamicness.  If it is possible, that's the way to go.  If it isn't, I don't think I should inflict object initialization on all invokers when the common case is just `help` and maybe `short`.

**Comment by c-blake** [comment]
Oh, by the way, I think if you find yourself using `dispatch(xyz, help={}.., many_of_the_same_args)`, it is also probably easy to write a wrapper `template` or `macro`, say `myDispatch`.  That would just call `dispatch` with all those standard parameters plus whatever new ones the caller passes to `myDispatch`.  Maybe you should figure that out and submit some `test/AbbreviatedDispatch.nim` file.  That approach probably wouldn't work in a `dispatchMulti` context, though.  Well, not with a _simple_ wrapper macro.

**Comment by timotheecour** [comment]
>  I think if there is a lot of repetition of named parameters for picky CLI authors we should figure out how to do that in Nim. I'm not at all sure that's possible given staticness vs dynamicness. If it is possible, that's the way to go

a macro should be able to do this

**Comment by c-blake** [comment]
Also, while a `dispatchMulti` abbreviator macro would be very `cligen`- specific, the `dispatch`-only one would probably not be.  Named parameters (along with CLI options!) almost always proliferate as projects age.  So, a generic enough macro might even be worth adding to Nim's stdlib (or at least being in Nimble somewhere on its own).

Say, a `wrapGen` (not unlike `dispatchGen`) that lets the user specify first a name, then fixed positional, finally any number of named parameters.  It would then create a `myDispatch` or whatever named wrapper which calls the wrapped name with the first N fixed, and the rest of the named params after the ones given to `wrapGen`.  I bet something like this could be pretty popular.

**Comment by timotheecour** [comment]
ya i see what you mean; probably not too hard to do, and would make sense in macros.nim; btw just making sure you saw https://github.com/c-blake/cligen/commit/4a8c262e68c71adf81dda464d879afe7bf9ec63f#commitcomment-31244947 ;-) ?

**Comment by c-blake** [comment]
So, I was working more on `dispatchMulti`, using it myself, and extending it for of-suspect-end-user-value "deep hierarchies". In that multi context, the dispatch parameter object passing idea has more intrinsic value since parameter list sites are not ordinary Nim call sites and some general "currying-esque" macro would likely not work so well.  I also think we can keep backward compatibility pretty painlessly by either picking a new name for the object taking variants like `dispatcher/dispatcherMulti` or by relying on overload resolution (though that is harder for `dispatchMulti` where this feature matters more).  We can just have the current long-param-list construct init some objects and call the short one.  We could eventually deprecate the long one, or not.  There's no real harm to leaving it (except having to add any new parameters in both places, but that's only `cligen`-internal harm).

All I ever personally pass in my own commands is `help=` and `short=`, but then I also control the defaults, and I don't wrap many pre-existing APIs beyond my control. You seem like you might pass more parameters (or less out of laziness? - hard to tell from our exchanges). You also seem pretty opinionated, more vested in this feature, and who doesn't love a good ontological exercise?

So, I thought I'd fly this by you before I do much more.   Here `CGFoo` is some proposed Nim type name. The comment to its side describes the category.  I left initializers in place just for context/out of laziness:
```Nim
#CGHelp     ## controls for appearance of the generated help
cmdName: string = "",
doc: string = "",
help: typed = {},
usage: string=dflUsage,
prelude="Usage:\n  ",
helpTabColumnGap: int=2,
helpTabMinLast: int=16,
helpTabRowSep: string="",
helpTabColumns: seq[int] = helpTabColsDfl,
mandatoryHelp="REQUIRED",

#CGBinding  ## controls for Nim API-CLI binding
dispatchName: string = "",
mergeNames: seq[string] = @[],
shortHelp = 'h',
short: typed = {},
positional: static string = positionalAuto,
suppress: seq[string] = @[],
mandatoryOverride: seq[string] = @[],
implicitDefault: seq[string] = @[],

#CGDispatch ## controls for what generated dispatchers do upon invocation
echoResult: bool=false,
noAutoEcho: bool=false,
version: Version=("",""),
docs: ptr var seq[string]=nil,
setByParse: ptr var seq[ClParse]=nil)

#CGSyntax   ## controls for command-line syntax
requireSeparator: bool=false,
sepChars={'=',':'},
opChars={'+','-','*','/','%','@',',','.','&','|','~','^','$','#','<','>','?'},
stopWords: seq[string] = @[],
```
I'm open to any different categories/different groupings/sub-grouping ideas you may have.  Some things were easy like everything related to how output is rendered going into `CGHelp`.  Others like `mergeNames` and `positional` were kind of hard to categorize, but I'd probably prefer categories that are more vague to shoe horn them into rather than keeping them as separate parameters/being in their own type.  Thoughts?

**Comment by c-blake** [comment]
Your github activity seems to have crashed.  So, I suspect whatever is behind that crash is probably more behind your non-response than a lack of opinion?  I'll probably give it another month or so before I commit something on this.

**Comment by c-blake** [comment]
Actually, a better idea would be to just lift out from the `dispatchGen` signature the 11 "very likely program-global" parameters:
```
usage     prelude   mandatoryHelp
sepChars  opChars   requireSeparator
helpTabColumnGap helpTabMinLast
helpTabRowSep    helpTabColumns
shortHelp
```
while leaving the remaining 16 "specific to a wrapped proc/internal" keyword parameters in place.  That would reduce params from 27 down to 17, but more importantly encapsulate all the "CLI author style" parameters in one place for people not in control of package defaults.  Then they could just set them once in an instance of some new `CligenConfig` type and pass that instance in every subcommand or in a multiple .nim file setting arrange an `include`/`import` and just re-use that.

Of those 11, only `shortHelp` is really questionable in my mind.  That *might* depend upon the wrapped `proc` if one had a parameter with a very natural non-help `-h` abbreviation (e.g. `--hash`) and wanted `-?` for that one proc only.  Consistency within a multi-command would make more sense than per-`proc` variation, though.  (`version` might be global for a given multi-command, but vary a lot from program to program, and a separate global variable `cligenVersion` already makes it easy to share versioning in a `dispatchMulti` setting, anyway).

Honestly, I wouldn't be surprised if there was no user that even used **any** of the 11 params above to worry about the backward incompatibility of just lifting them out and replacing with a new entity.  Of them all, I think only you (@timotheecour) ever asked for a change in any, namely `mandatoryHelp` -> `"REQUIRED"`, and that package default is what you wanted.  Well, `helpTabColumns` was also by request, and his request isn't the package default...and maaaybe someone might tweak the `usage` template which was always there.  Even so, I'm kind of inclined to force minor code edits on those tweakers, maybe call it cligen-1.0 and promise to not cause any more big disturbances.
