### ISSUE TITLE
A way to suppress all "short" options?

### ISSUE THREAD

**Issue by pb-cdunn** [c-blake/cligen#5]
When I have a large number of options, the short options only confuse the user. What if `short={}` -- with an empty dictionary -- simply suppressed them all?

**Comment by c-blake** [comment]
Right now ``short={}`` means "do not override any guessed short option bindings".  It would be very easy to add a ``noShort=false``, though.  It might be best of all to have a ``NUL/'\0'`` character in ``short`` indicate no short option (a zero byte short option is never possible/convenient since ``argv[]`` are ``NUL`` terminated strings).  Then you can turn off a short option for any specific named parameter.  This scheme could be generalized to have some magic string key that is an illegal Nim identifier which means "all parameters", maybe the empty string, as in ``short={ "" : '\0' }`` to suppress all short options.

**Comment by pb-cdunn** [comment]
Hmmm. This doesn't help much. The point is that, while the long options are *always* useful, the short options become less and less useful the more options we have. So this solution does not scale well.

I really want to be able to turn off short options completely.

**Comment by c-blake** [comment]
That is part of the general solution I committed.  See test/NoShort.nim for what you want.  I just thought it also made sense to be able to suppress any given short option as well...E.g., make the user spell out --really-do-this or something for an important one, but let them still abbreviate other less critical things like -v for --verbose, etc.

**Comment by pb-cdunn** [comment]
>  To suppress all short options, give short a key of "".

Oh, I understand now. Thanks.
