### ISSUE TITLE
`distinct type` in param gives CT error

### ISSUE THREAD

**Issue by timotheecour** [c-blake/cligen#56]
```nim
type Age = distinct int

proc main(age: Age)=
  echo (age,)

import cligen
dispatch(main)
```

Note: maybe `sugar.distinctBase` which I had added in a previous PR could come useful for that, idk

**Comment by c-blake** [comment]
I agree that it would be nice to make it easier on users, but since `distinct` is intended to block overloads like `argParse`/`argHelp`, this behavior is "just as intentional".  The user in this case can just define to very small procs:
```Nim
type Age = distinct int

proc main(age: Age)=
  echo if int(age) == 4: 1 else: 2

import cligen, cligen/argcvt

proc argParse(dst: var Age, dfl: Age, a: var ArgcvtParams): bool =
  var iDst: int
  result = argParse(iDst, int(dfl), a)
  dst = Age(iDst)

proc argHelp(dfl: Age; a: var ArgcvtParams): seq[string] =
  argHelp(int(dfl), a)

dispatch(main)
```
Note that I changed your `echo (age,)` to something else for testing since `echo age` fails (as intended as hitherto mentioned) and `echo (age,)` only produced inscrutable output like:
```
(Field0: ...)
```
I will include this as a new example in `test/DistinctInt.nim`, though.  I think Nim itself needs changing to make it any easier.
