### ISSUE TITLE
cligen accepts invalid syntax, eg: --flag@=foo

### ISSUE THREAD

**Issue by timotheecour** [c-blake/cligen#58]
test case: see D20181130T093828 in https://github.com/timotheecour/vitanim/blob/master/testcases/tests/t0000.nim

**Comment by c-blake** [comment]
Yeah.  There is probably other invalid syntax accepted.  PRs welcome.

**Comment by c-blake** [comment]
Also, partly why this one is not flagged as an error to the user is because operator interpretation is left open to `argParse`.  Right now I just treat any unrecognized operator as like regular assignment.  I wasn't sure if it would be user friendly or hostile to do otherwise.  On the one hand, maybe users want to know when they mis-type.  On the other, they might be annoyed to hear it.  So, I just went with "ignore not understood".

**Comment by c-blake** [comment]
While someone can always override the `argeParse` overload, maybe there should be a new global variable that a CLI author sets to control default `argParse` strictness?  A CLI author knows his CLI users better than I ever can { unless I am one in the same :-) }.  It may depend on what action is being done.  Something dangerous like an "rm -rf" might want users to know they typed some garbage before anything happens.  Something else might want to just press onward.

**Comment by c-blake** [comment]
I decided default to failing was better, but provided a way to get the old loose behavior back and a new mechanism for other argcvt syntax handling tweaks.

**Comment by timotheecour** [comment]
thanks! failing is better indeed, as you did in your patch
