### ISSUE TITLE
dispatch(main, positionalSeq:false) option for treating seq param as non-positional (positional = "" doesn't work)

### ISSUE THREAD

**Issue by timotheecour** [c-blake/cligen#62]
followup from https://github.com/c-blake/cligen/issues/61#issuecomment-443306092
`positional = ""` doesn't seem to work: 
test case: see D20181130T150307 from https://github.com/timotheecour/vitanim/blob/master/testcases/tests/t0000.nim

## proposal: add `positionalSeq` bool flag to dispatch:
dispatch(main, positionalSeq:false) # by default: positionalSeq:true so no breaking change

note, it'd be future compatible with following potential proposal:

## potential proposal: `positionals`
allow specifying which arguments are positional, eg:
```nim
proc main(foo1: int, foo2: float, foo3: string, foo4: seq[string])=discard
dispatch(main, positionalSeq:false, positionals:["foo2", foo4"] )
./app --foo1:10 --foo3:myfoo  3.14 hello world # sets foo2 to 3.14 and foo4 to @["hello", "world"]
```
when unset, positionalSeq would be empty and imply existing behavior; would be compatible with positionalSeq:false

**Comment by c-blake** [comment]
I'll look into fixing that behavior tomorrow, but about your potential proposal -- aren't you the one who had me turn my old mandatory positionals into --key:value instead?

**Comment by timotheecour** [comment]
yup, and I definitely prefer the new way as default, but when converting existing cmd line interfaces to cligen it makes sense to have `positionals` available as an option sometime in the future; that's why i'm calling this `positionalSeq:false` instead of `nopositional:true`, which would not work well with that `positionals` potential future feature

**Comment by c-blake** [comment]
FWIW, I think just the current positional="" or nil working and a single new `positionals: seq[string] = @[]` would cover it, where empty just implies false and non-empty true.  Anyway, there are some real complexities to think about such as how mandatory these are vs. just updating param values if they happen to be available and that sort of thing.  It could get to be a pretty hairy interface (which then undermines the conversion to cligen being better than some old way, if that is the context).  And there is `setByParse` now.  Maybe there needs to be a `clArgKind` parse status, too, (to include these non-option positionals).  Then you could do it that way, too.

**Comment by timotheecour** [comment]
btw nil doesnt work anymore in recent nim, by design

**Comment by c-blake** [comment]
Well, it works a little, at least with `ptr`s.  I was just using it today for `setByParse`.  I guess maybe it doesn't work for string is what you mean?

**Comment by timotheecour** [comment]
correct, what doesn't work anymore (by design) is nil for string and seq

**Comment by timotheecour** [comment]
and sure, making `positional="" ` work (instead of adding `positionalSeq:false`) would be an ok fix too, and maybe even better (more orthogonal)

**Comment by c-blake** [comment]
Well, in light of `nil` not working with `string` anymore, I will probably change the default value for `positional` to `"<auto>"` or some other illegal Nim identifier and have "" turn off any inference about the main positionals.  I feel like the lion's share of commands take some `seq[]` something.  While that isn't true of `proc`s, it always seemed to me more-likely-than-not true of a proc someone wants to wrap into a command.  It's certainly worked out that way in command's I've written with cligen.  Plus, it's a default that dates back to the first release and would be very breaking to change it now without a really compelling rationale.

**Comment by c-blake** [comment]
So, I haven't really tested `positional=""` much, but the logic was pretty simple.  It should behave as if there were no `seq[T]` params at all, i.e. do no inference.  Once `posIx == -1` all that gets turned off.  Let me know if this works.

(And by "work", I mean work as intended.  I realize you might not like the default `positional="<AUTO>"`, but I really do think there are whole shell idiom universes/sub-syntaxes are built around the idea of "some seq" being in there..Much of the utility of globbing, for example.  So, I think it's a good default, and also very likely used by someone else if there is any other cligen user which I think there are. )

To do your other proposal is thinkable, but a bit of work.  Probably `posIx` needs to become a `seq` instead of an `int`.  Then, in one of the several loops over all params, one needs to build up `argParse` calls that would be wedged in at the `postInc` part of the case clause in `defNonOpt`.  These names in this potential new `positionals` could all have different Nim types.  So, we'd probably need to generate a case statement there switching off `posNo` where each `of` did the right set-up for that parameter.  When that now `seq posIx` is consumed the "rest" would get sent to whatever `positional` (singular!) specifies -- CLI-author specified, inferred, or nothing.  In the case of nothing, we'd just do a `clNonOption`/raise ParseError as we do now.  Maybe `initalPositionals` would be a better name.

**Comment by c-blake** [comment]
(Oops - `initialPositionals`.)

Also, there's obviously help message work to be done.  Probably a syntax like I had before you made me change mandatory parameters makes sense with `{}`s as in `foo [optional] {required}`.  Most documentation seems to use `[]` and `{}` that way.

Then there is also the new "user understood type" stuff we just added for https://github.com/c-blake/cligen/issues/60 in your PR...*and* default values..  basically whole snippets of the proc param in the Nim..`./foo {alpha: float} [beta: int=42]`.  It gets pretty noisy pretty fast and so doesn't scale to many parameters.  This is a deal breaker, but we might need line wrapping there with backslashes or indentation to visually cue the reader what's going on.  The message could get ugly.

It can also get pretty confusing, for CLI authors and CLI users alike.  Let's follow up on my "real complexities" comment a bit above in this thread. In this new `initialPositionals` World Order, the proc parameters could have explicit default values but still get "hard-allocated positional slots".  E.g., if there is any mandatory value *after* defaulted values then really the defaulted ones cannot really be optional since there is no way to identify what goes where unless the sequence is populated up to the last non-optional.  I.e., "foo [a=3] {b}" makes no sense since there is no way to bind `b` if the user gives no `a`.

So, `a` cannot be optional even if the proc has an explicit default value, but this breaks the very simple `cligen` explicit default rule about that.  That rule that is kind of at the heart of simple type inference and simple API<->CLI mapping in terms of mandatory inference..so simple it needs almost no elaboration.  You see an example and you get it.  Of course I have `implicitDefault` and `mandatoryOverride`, too.

Anyway, to press onward, saying we're willing to special case here, we would then also have to suppress the default value the API author provided _in favor_ of mandating CLI user's enter it.  That is going to be right _almost never_. A param bothersome enough for a Nim programmer to not need entering, but _not_ bothersome for a CLI user who probably types it many more times?  Of course, interfaces can evolve and what had been defaulted in the proc might become not-so or vice-versa.

So, at the least this should be discouraged/noted by the `cligen` system to make the CLI author consider parameter order more compatible with the API author.  We might be able to generate a compile-time warning if the order in `initialPositionals` created this kind of ambiguity -- `cligen: treating "a" as mandatory in initialPositionals even though defaulted due to subsequent non-defaulted params`.  If something like this changes, the CLI author may need to hear it at compilation time to at least be prodded into some kind of help message/documentation to the CLI user.

Anyway, this is all quite a bit of work and should at least wait until after `setByParse` is finished and this release is punched out.

**Comment by timotheecour** [comment]
your patch for `positional=""` works fine, thanks!
the 2nd item (`positionals ` / `initialPositionals`) can be dealt later indeed
