### ISSUE TITLE
`--help-syntax` : provide help specific to cligen syntax

### ISSUE THREAD

**Issue by timotheecour** [c-blake/cligen#64]
as mentioned here: https://github.com/genotrance/nimterop/issues/11#issuecomment-443420428
```
./app --help
--help: prints this help
--help-syntax: prints additional help regarding advanced cligen-specific syntax
...
```

--help-syntax would provide cligen specific help, so as not to clobber the main --help (so users familiar with --help-syntax don't have to read it over and over)

if the cli has a DPSV:

```
the delimiter is specified in 1st position, and can be any char, eg:
--foos=,arg1,arg2: foos is set to "arg1" "arg2"
--foos^=,arg1,arg2: foos is prepended by "arg1" "arg2"
--foos+=,arg1,arg2: foos is appended by "arg1" "arg2"
--foos@= foos : is cleared
```

if the cli has a ,SV:

```
--foos=arg1,arg2: foos is set to "arg1" "arg2"
--foos^=arg1,arg2: foos is prepended by "arg1" "arg2"
--foos+=arg1,arg2: foos is appended by "arg1" "arg2"
--foos@= foos : is cleared
```

Note: no need to expand --help-syntax for all the flags (eg instead of expanding this msg for  --foos1 --foos1 if there are 2 flags foos1, foos2, just provide syntax for a single, generic, flag named "foo" ; it's clear enough)

## note
I'd like `cligen` name mentioned in --help-syntax so users seeing it for 1st time know it comes from cligen (may help spread its use)

**Comment by c-blake** [comment]
This all seems pretty reasonable and is roughly what I was thinking, probably with a `dispatch` arg to define some kind of help message template (since dispatch-callers can also override `argParse`/`argHelp`).

**Comment by c-blake** [comment]
I'll probably work on something for this tomorrow or the next day.  All this aggregate handling syntax you had me add is pretty non-standard and warrants description.  Maybe at Google there is one or more libs with standard semantics/`+=`.  Dunno.  It's common in programming languages, but not command syntaxes in my experience.

I agree it's sort of nice and sidesteps whole new options/option-families (`--no-std-includes`, I'm looking at you...).  Stronger aggregate syntax seems better.  People may never really have instincts for how to use it, though, since it's more capable than other kinds of CLIs.  So, that's a good reason to have `cligen` mentioned in there, too.

In compilers and such `-Ddef1 -Ddef2 -Ipath1 -Ipath2` are aggregating.  So, I went with "append if no operator, but clobber if explicit operator" to try to get something people at least might discover if they just tried out a couple things.  That seemed more natural rather than have clobbering be a new operator, though we could add a clobber operator for clarity of intent like `+=` is there for clarity.

**Comment by c-blake** [comment]
I added this feature and closed out this issue, but I'm basically 100% sure you'll have a lot of things you want to change/add in `cligen/helpSyntax.nim`.  We can just work on that as PRs.
