### ISSUE TITLE
keyword arguments to dispatch should work if they're passed as const variables

### ISSUE THREAD

**Issue by timotheecour** [c-blake/cligen#66]
```nim
import cligen

proc main(age = 23, foo: seq[string])=
  discard

when defined(case1):
  # works:
  dispatch(main, positional = "<AUTO>")

when defined(case2):
  # BUG: fails:
  # Error: requested positional argument catcher mypositional is not in formal parameter list
  const mypositional = "<AUTO>"
  dispatch(main, positional = mypositional)

when defined(case3):
  # BUG: silently ignores `myhelp`
  const myhelp = { "age" : "comment age" }
  dispatch(main, help = myhelp)

when defined(case4):
  # works
  dispatch(main, help = { "age" : "comment age" })
```

**Comment by c-blake** [comment]
Yeah.  The code in `posIxGet` just does a string literal check since that's the macro param default, and then `""` is also a literal, and I'd expect any user pass would also be a literal.  To be honest, I might prefer non-strings here and in a few other places where the CLI author passes parameter names.  We'd have to carve out a legal identifier to signal "<AUTO>" and "", and probably other things, too.  I wasn't sure how nice all that could be made.  So, I just went with strings.

**Comment by timotheecour** [comment]
i have a fix pending, bear with me...

**Comment by c-blake** [comment]
Well, I merged your PR, but haven't tried to run your test.  If you're satisfied you can close this issue.

**Comment by timotheecour** [comment]
the PR only fixed the case of `positional` param  (but paved the way for other params to be fixed in same way, allowing user to pass param via a const instead of inline), so have to keep open for other params
the `help` is a bit problematic (IIRC) but others should be straightforward

**Comment by timotheecour** [comment]
=> https://github.com/nim-lang/Nim/issues/9863

**Comment by c-blake** [comment]
Ok.  I'm not sure how much CLI authors will really want to be putting variables rather than literals in those slots in practice/how much this issue matters.

**Comment by timotheecour** [comment]
* feel free to close, at least there's a place-holder if we want to convert some flags to static; 
* for flags like `help`, this is useful (eg if help is generated via some other mean for eg); unfortunately, currently `help` is weirdly typed (doesn't seem typed like a table for eg)

**Comment by c-blake** [comment]
Yeah, but that association list `{:}` literal is nice.  It's what people are used to from other languages like Python.  I'm fine re-typing `help` if we can keep that initializer syntax.

**Comment by c-blake** [comment]
Note that I just added this ability to resolve https://github.com/c-blake/cligen/issues/110 and https://github.com/c-blake/cligen/pull/130 and see `test/PassValues.nim`.  The `help` parameter can now be either an initalizer a-list or a `const Table[string, string]`.

**Comment by 0xACE** [comment]
I followed the activity on this repo the past few days, and I would like you thank you for your work :D

> Ok. I'm not sure how much CLI authors will really want to be putting variables rather than literals in those slots in practice/how much this issue matters.

I also wanted to mention that I find it useful to use variable rather than literals as it allows me to use simple `new.nim` template files to quickly configure files. With variables I can leave them at the top to let me quickly configure the program rather than rewriting my usage of `cligen` each time I use it (practically all my programs use cligen).

**Comment by c-blake** [comment]
You are welcome, and thanks for the thanks.  Open source is usually a thankless job.

I get that you/others have use cases where you really like it and that's why I left that other issue open for so long.  I am usually pretty aggressive at closing what I consider to be off-track issues to preserve usability of the issue list as a TODO list.  Hence zero open issues now for the first time in a long while!  I should maybe declare 1.0 status.  I have some XXX items internally, but I doubt they will change public interfaces.

Personally, I usually do all the CLI driving at the bottom guarded by `when isMainModule:`  to ensure preserving access via `import myMod` and `myMod.apiCalls` with some `myMod.nim`.  As you may know, I view preservation of Nim-callability as one of the "emergent" selling points of this entire approach to CLIs.  Yes, there are many other selling points, and I suspect the "zero friction/if you know Nim then you already *know* the 'API'" probably wins people over the most.  Sometimes this emergent property is even more practical than esthetic (about shell syntax). Starting up processes can take 100 microseconds to several milliseconds or worse with network file system involvement.  So, a shell loop solution can be 1000s of times slower than a native language loop for situations where many invocations are needed.  Visual separation of top/bottom/how you build/write parameter lists to things like `dispatch` is orthogonal to Nim-callability, though.

Besides the situation you mention, sometimes (e.g. in an `initGen` setting), it makes even more sense to put all that "help meta-data" nearby the type definition "primary data" at the top of a file. (I do this in my `lc`.)  I only really held off on all of this because @timotheecour's `static` solutions seemed to press hard on these iffy/buggy/tricky areas of Nim, but the new `if n.kind == nnkSym: n.getImpl` meta-solution seems more robust.
