### ISSUE TITLE
escaping delimiter for a seq[string]

### ISSUE THREAD

**Issue by timotheecour** [c-blake/cligen#70]
right now there's a bit of an issue in escaping `,` (or whatever is used as delimiter), in case the param we give contains the delimiter (delimiter is controlled by cli author, but cli user may want to have a string that contains the delimiter, and there's no way to escape it right now)

## proposal: escape delimiter x with \x:
```
./app --foo.='foo\,with\,commas'
```
note that to pass `\` itself we can do: `\\`

## alternative: new assignment syntax
need to support assign, append, prepend:
```
./app --foo|=foo,with
./app --foo|^=foo,with
./app --foo|+=foo,with
```

**Comment by c-blake** [comment]
This is where DPSV aka `s/pat/sub/` style is useful.  I considered pretty seriously having that be the default not ,SV.  I also considered not having any splitting/multiple elements at once at all but just forcing multiple `+=`.  This is really what most users would probably expect, IMO, and might be the cleanest solution.  That only works for 1-dimensional things like `string/set/seq`, but that's all that's supported right now anyway.

I'm not sure I even understand how your new assignment syntax solves the problem or why foo is repeated.  Given that things like `+=` are already aggregating across argv elements, we could also have a non-delimited/only-one-at-a-time aggregate update operator and a splitting operator.  Maybe that's what you mean.

Anyway, I think the backslash approach is easy...just have some unescape preprocessing around `unescape(src, delim).split(delim)`..and probably closer to what some hypothetical user would guess/remember easily.  So, that's probably the way to go.  Of course, the shell uses `\` as an escape, too.  So, that won't be easy on people, but it'd at least be possible.

**Comment by c-blake** [comment]
What do you think about just killing all the delimiting and requiring CLI users to re-issue the option with another argument?  It side-steps a whole host of complexities.  As long as we keep `@=` and `+=` (or just no `=`) all the functionality will be preserved.  Sometimes more typing will be necessary, but more explanation never will be.  I think the only reason I did all that delimiting in the first place was as a natural inverse to the delimiting I did to display the default value in the table.

**Comment by timotheecour** [comment]
syntax sugar for delimiting is nice though, let me think about it overnight

**Comment by c-blake** [comment]
Something else that might also work better is have the default be the no-need-for-explanation-what-almost-any-other-CLI-does version and provide a `cligen/delimiterSV.nim` and also a `cligen/delimPfxSV.nim` and so on.  Then if CLI authors really like some particular delimited syntax and want to provide that to their CLI users, it's just one more line between `import cligen` and `dispatch` -- `include cligen/<DELIM-SYNTAX>`.  These might files might also form easily digestible examples for CLI authors defining their own syntax when/if required.  CLI authors already have to tweak delimit which refers to stuff only documented in `argcvt.nim` / internals.  It's also a little more in-your-face to the CLI author that they may need to explain something less-standard to a CLI user.

**Comment by c-blake** [comment]
Also, we could \\-quote commas in default values in this new no-aggSplit setup.  This value would not be what a user is expected to enter, exactly, but it could mitigate confusion about what the default value actually is in the rare case it contains a comma.  None of the ,SV value strings listed in the help would be expected entry, anyway.  They'd be _expected_ to go `--opt A --opt B ...` or maybe with `^=`s or `@=`s in there if they wanted, which is what `--help-syntax` would tell them.

**Comment by c-blake** [comment]
Well, except for maybe escaping things in the help table, I think this issue is resolved.  Honestly, with DPSV the help table default value is always going to be _able_ to look quite different from what a user might type.  It's a no-escaping/no-quoting necessary style which is it charm, after all.

If we do escape whatever arbitrary delimiter we choose for the help message (based on, say, scanning the default `$`s and seeing if the char is in there), we would probably also have to add backslash or otherwise delimiter quoting/unescape for the strings, too.  Not impossible, but all a bit distracting from the simplicity of DPSV CL users should focus on.  So, I'd say hold off on that unless/until we get complaints.

We could also keep the `delimit` parameter to `dispatch` and re-purpose it to just be the delimiter for the help message only.  The CLI author always knows (or can look up) the default Nim values for all those types and probably has a good idea how they render and if `","` is a bad separator string.

Anyway, this is now all about help message _maybe_-nice-to-haves.  So, I'm going to close it.
