### ISSUE TITLE
`./main -f` fails even though `./main -f:` or `./main -f=` or `./main --foo` works

### ISSUE THREAD

**Issue by timotheecour** [c-blake/cligen#72]
test case: see D20181203T173521 in  https://github.com/timotheecour/vitanim/blob/master/testcases/tests/t0000.nim

`./main -f` and `./main --foo` should both fail or both succeed; I'm leaning towards both fail (probably catches more bugs)

**Comment by c-blake** [comment]
As mentioned over in https://github.com/c-blake/cligen/issues/71, I changed my mind, but thought I'd elaborate on my rationale.  This is still a bug to fix, but it should succeed for `string` (or anything that accepts an empty string as a legitimate value).  If we provide an empty `val` string instead of error out in `parseopt3` (I think), things should error out at `argParse` for types that actually need a non-empty string.

This seems more consistent to me.  Otherwise early on in the command `--foo=""` would work (turned by the shell into just `--foo=` which we want to work just like `--foo` for consistency). Under the error out proposal, if I understand it correctly, `--foo=`  would succeed earlier than final, but fail as a final argument -- which sounds great at detecting early ENTER keypress mistakes -- _until_ you consider CL users might actually use empty string vals a lot.  Empty string can be a pretty useful "disable this" sort of value, like say "output to nowhere or a path", and maybe there's a path in a config file or environment variable you want to disable for a given run.  If they did use them a lot, not being able to use them just because it's EOL would probably be a huge annoyance.

If empty `string|seq|set` is dangerous input the proc should deal with it, as with any bad input - such could easily be used in a Nim call, for example.  For non-empty-strings, the `bad value ""` should be pretty clearly signal the mistake to a CL user in this case if a non-empty was expected.

Sound reasonable?  I hadn't considered the utility of empty strings before.
