### ISSUE TITLE
[minor] corner case: `proc main(h = "bar")` gives Error: duplicate case label

### ISSUE THREAD

**Issue by timotheecour** [c-blake/cligen#73]
test case: see D20181204T102517 in  https://github.com/timotheecour/vitanim/blob/master/testcases/tests/t0000.nim

a bit of a corner case but still.
Maybe best is to improve error message (eg, simply adding: `h` is reserved for `help`), so as to keep cli usages consistent (where -h always means help)

the argument in other direction (support -h to mean set that flag instead of calling help) is if we want to replace with cligen an existing cli application that already has a non-help meaning for -h

**Comment by c-blake** [comment]
Well, I kept a way to override the short help letter for situations like this.  We should probably error out with a message indicating that knob so that users can then override the short help letter with '?' and avoid the error.  That's what I did for the multiple non-defaulted possible positional catchers message (though you may not have noticed in the giant pile-o-changes!).

**Comment by c-blake** [comment]
In theory, we _might_ be able to auto-infer to use '?', but that is probably being too smart, IMO.  Letting the CLI author know and guiding how to fix is enough.
