### ISSUE TITLE
`iterates over each item of`

### ISSUE THREAD

**Issue by pb-cdunn** [c-blake/cligen#8]
Have you ever seen this?
```
$ foo.exe --help
Usage:
  run_foo [optional-params]
iterates over each item of `a`. iterates over each item of `a`.
  Options(opt-arg sep :|=|spc):
  --help, -?                                                                                          print this help message
  --test, -t                  toggle  false                                                           set test
  --stream, -s                toggle  false                                                           set stream
  --debug, -d                 toggle  false                                                           set debug
  --silent                    toggle  false                                                           set silent
  --n_core=, -n=              int     0                                                               set n_core
```
I have one program which does this and one which does not. The difference seems to be that the function dispatched to is in a different module (and a different directory) in the case above.

**Comment by c-blake** [comment]
I have never seen duplication like this.  I have seen corruption of the ``strVal`` for ``nnkCommentStmt``.  E.g., I saw the ``strVal`` be ``nil`` or be from other procs in the module instead of the correct one.  Both of those gitches I saw persisted for like 11 months and then went away without any specific compiler "fix".  I had an issue open  https://github.com/nim-lang/Nim/issues/3690 for this.

Possibly helpful to note is that my procedure for building Nim itself changed during those 11 months.  I had been using the stock Gentoo ebuild script that I think someone wrote many years ago just bumping version numbers, but I discovered that that build method was internally using some pretty old/stale Nim csources.  So, I switched to build my ``nim`` binary using the Travis/Continuous Integration build scripts in the Nim repository against a current checkout.  I have not seen any weird comment text glitches since then and no one else ever piped up to say they reproduced the failure I was seeing.

The errors I was seeing (``nil``/wrong proc text) smelled a lot like either something really broken in the compiler or version skew/mismatched compiler/VM internal kinds of issues.  It may have been the former and been fixed incidentally or the latter and been fixed by my changed build process.  In theory, I could use my current build process but with old git versions I know were failing to distinguish these two cases, but before doing that it makes sense to ask how you build Nim/get that ``nim.exe`` binary to make the ``foo.exe`` and make sure it's basically the way the automated Nim builds on github when people do PRs.

In terms of your final comment, two of my "automated tests" in ``test/`` dispatch to procs defined in other modules (``test/EchoResult.nim`` and ``test/External.nim``).  I run that test.sh script every time I update my Nim to the latest devel and haven't seen any glitches.  All this said, I doubt any other Nim'rs use that comment text except ``cligen``.  Also, I never use Nim or ``cligen`` on Windows.  So, it could be something Windows-specific.

**Comment by c-blake** [comment]
Hi there.  Were you ever able to test this issue any further in light of my above comments?

**Comment by pb-cdunn** [comment]
It's still happening, with the very latest nim/devel. And I also see something weird in a different executable:
```
Usage:
  main [optional-params]
same as `assert` but is always turned on and not affected by the
``--assertions`` command line switch. same as `assert` but is always turned on and not affected by the
``--assertions`` command line switch.
  Options(opt-arg sep :|=|spc):
...
```

**Comment by c-blake** [comment]
Yeah...Picking up the `strVal` from the `nnkCommentStmt` for `lib/system.nim:doAssert`.  How do you build nim?  Do you use the standard build script `ci/build.sh`?  Do my two automated tests I mention pick up the wrong comment text as well or just your program(s)?

**Comment by pb-cdunn** [comment]
> In terms of your final comment, two of my "automated tests" in test/ dispatch to procs defined in other modules (test/EchoResult.nim and test/External.nim).

Where are these tests? I don't see them:
```sh
$ find .
.
./.git
./.gitattributes
./.gitignore
./.travis.yml
./config.nims
./examples
./examples/binext.nim
./examples/example.nim
./examples/gotchas.nim
./examples/restriction_example.nim
./msgpack.org.md
./msgpack4nim.nim
./msgpack4nim.nimble
./readme.md
./msgpack2any.nim
./msgpack2json.nim
./tests
./tests/basic.json
./tests/basic.mp
./tests/nim.cfg
./tests/test_any.nim
./tests/test_codec.nim
./tests/test_json.nim
./tests/test_spec.nim
./tests/tests.nim
```

**Comment by c-blake** [comment]
Um, that doesn't look like my git repo at all.  https://github.com/c-blake/cligen/tree/master/test/ is the subfolder with tests.

As mentioned above, test/EchoResult.nim and test/External.nim are probably the most relevant to this issue.  At the top level there is a `test.sh` driver script, but it really just compiles things, runs the `--help` and compares all that output against the expected file (`test/ref`).

From the top level of a git clone, you should be able to `nim c test/EchoResult.nim` and then run `test/EchoResult --help` without any script.  It's _supposed_  to pick up the doc comment on `strutils.editdistance`.  When I saw the trouble that seemed like what you are seeing it would instead pick up either nil comments or stray unrelated doc comments in the `strutils` module..much like your text looks like it's from the doc comment of some iterator in `system.nim` not the proc you are wrapping with `cligen.dispatch`.

Anyway, while there may be no other users of this Nim feature (getting doc comments from `getImpl`) besides `cligen`, it is more a bug/issue with Nim than with `cligen`.  Here is another test program you could try with your build:
```Nim
import macros

proc commentsRec(n: NimNode) =
  if n.len > 1:
    for kid in n: commentsRec(kid)
  else:
    if n.kind == nnkCommentStmt: # node there; .strVal/.comment always nil
      echo "found a comment"
      if n.strVal != nil: echo n.strVal

macro comments(n: untyped): typed =
  echo "Collecting comments"
  commentsRec(n)

proc foo(a=1, b=2) = ## my first doc comment
  ## my second doc comment
  echo "yadda"

discard comments(foo.symbol.getImpl)
```
For me, strangely, this above program _fails_ to find the doc comments even though all my usual `cligen` invocations of `getImpl` succeed!  So, it may be that we need to re-open a compiler issue.

**Comment by pb-cdunn** [comment]
Some warnings:
```
$ nimble install cligen
       Info Hint: used config file '/home/UNIXHOME/cdunn/repo/gh/Nim/config/nim.cfg' [Conf]
       Info home/UNIXHOME/cdunn/repo/gh/Nim/lib/system.nim(470, 35) Warning: unknown magic 'Exception' might crash the compiler [UnknownMagic]
       Info home/UNIXHOME/cdunn/repo/gh/Nim/lib/system/nimscript.nim(15, 19) Warning: unknown magic 'BuildOS' might crash the compiler [UnknownMagic]
   Warning: Package 'cligen' has an incorrect structure. The top level of the package source directory should contain at most one module, named 'cligen.nim', but a file named 'argcvt.nim' was found. This will be an error in the future.
      Hint: If this is the primary source file in the package, rename it to 'cligen.nim'. If it's a source file required by the main module, or if it is one of several modules exposed by 'cligen', then move it into a 'cligen/' subdirectory. If it's a test file or otherwise not required to build the the package 'cligen.nim', prevent its installation by adding `skipFiles = @["argcvt.nim"]` to the .nimble file. See https://github.com/nim-lang/nimble#libraries for more info.
Downloading https://github.com/c-blake/cligen.git using git
       Info home/UNIXHOME/cdunn/repo/gh/Nim/lib/system.nim(470, 35) Warning: unknown magic 'Exception' might crash the compiler [UnknownMagic]
       Info home/UNIXHOME/cdunn/repo/gh/Nim/lib/system/nimscript.nim(15, 19) Warning: unknown magic 'BuildOS' might crash the compiler [UnknownMagic]
  Verifying dependencies for cligen@0.9.6
 Installing cligen@0.9.6
   Success: cligen installed successfully.
```

**Comment by pb-cdunn** [comment]
(I needed to update **cligen**.)

Yes, your examples work for me. But with the latest **nim** and the latest **cligen**, I still have the same problems.

```
$ cat fc_rr_hctg_track2.nim
from falcon.rr_hctg_track import nil


when isMainModule:
  import "cligen/cligen"
  # cligen supports --foo-bar and --foo_bar styles automatically.
  dispatch(rr_hctg_track.run_stage2)

$ ./fc_rr_hctg_track2.exe --help
Usage:
  run_stage2 [optional-params]
iterates over each item of `a`. iterates over each item of `a`.
  Options(opt-arg sep :|=|spc):
...

$ ./fc_consensus.exe --help
Usage:
  main [optional-params]
same as `assert` but is always turned on and not affected by the
``--assertions`` command line switch. same as `assert` but is always turned on and not affected by the
``--assertions`` command line switch.
  Options(opt-arg sep :|=|spc):
...
```
Oddly, `fc_rr_hctg_track.nim` (without the `2`) works fine. It differs from `track2` by having `main()` inside itself.

Here is my repo: https://github.com/bio-nim/nim-falcon/tree/dev

**Comment by c-blake** [comment]
Ok.  I was able to copy your repository, reproduce the behavior you describe on Linux, and figure out a workaround for you.  First, you need to use two '#' for a comment to be a documentation comment and get a NimNode.  Your existing program text reads like "# Stage 2" with just a single '#'.  Change that to '##' and use the current cligen and you will get the correct string extraction.  (Well, even with the old cligen you should get the _new_ text after a proper ## doc comment, but the new one lowers a depth limit on the doc comment node to block that stray "iterates over" text from getting used.)
