### ISSUE TITLE
Any idea why this happens?

### ISSUE THREAD

**Issue by pb-cdunn** [c-blake/cligen#96]
```nim
     Error: Build failed for package: pb
        ... Details:
        ... Execution failed with exit code 1
        ... Command: "/mnt/software/n/nim/0.19.9/Nim/bin/nim" c --noBabelPath -d:release --path:"/scratch/cdunn/repo/nim-falcon/nimbleDir/pkgs/cligen-0.9.19"  -o:"/localdisk/scratch/cdunn/repo/utils/pb" "/localdisk/scratch/cdunn/repo/utils/src/pb.nim"
        ... Output: pb.nim(8, 11) template/generic instantiation of `dispatch` from here
        ... ../../nim-falcon/nimbleDir/pkgs/cligen-0.9.19/cligen.nim(674, 14) template/generic instantiation of `dispatchGen` from here
        ... ../../nim-falcon/nimbleDir/pkgs/cligen-0.9.19/cligen.nim(573, 5) Error: 'from' is only allowed at top level
```
Oddly, this does not happen for another package, using the same `$NIMBLE_DIR`. Here is my simple program:
```nim
import cligen

proc main(extras: seq[string], int_dummy: int = 42, string_dummy: string = "hello") =
    echo "pb main"

if isMainModule:
  dispatch(main, short={}, help={})
```

**Comment by pb-cdunn** [comment]
Even simpler:
```nim
import cligen
import os

proc main*(): int =
    echo "pb main"

if isMainModule:
  dispatch(main)
```
Same error!

**Comment by pb-cdunn** [comment]
```nim
if isMainModule:
```
must be
```nim
when isMainModule:
```
Of course!

**Comment by pb-cdunn** [comment]
Btw, this is super cool:
```nim
% ./pb data -h
Unknown subcommand "data".  Maybe you meant one of:
        dataset
```
Great idea!

**Comment by c-blake** [comment]
Glad you figured out your mistake.

On the topic of your final comment, did you read my message about maybe doing Mercurial/gdb/gnuplot-like acceptance of the shortest uniquely identifying prefix command/option/enum value?  In this example, the command would have just executed if you had no other commands prefixed by "data".

That idea has a strong flavor of Do What I Mean / I don't care how verbose the CLI author made things, I'm going to use the short way.  Indeed, it creates almost a middle-step from "short options" to "longest options" with this intermediate shortest matching prefix "long-ish" option/string matching.

It doesn't really obsolete the suggestion framework, though it might make more sense to expand that to understand the difference between "does not match a *unique* prefix" vs "no string starts with that prefix".  and, of course, like the long options, subcommands, and enums it would apply to all three cases.  It probably helps more in multi-command/enum settings.

It's kind of a rare/obscure feature, though in some ways multi-commands are all a bit more rare/idiosyncratic.  Personally, I like it a lot.  One of the frustrations I have moving between mercurial and git repos is git requiring all this specificity..I miss just "st" instead of the longer "status".  But I get that people (especially detail-oriented programmers) also want specificity.  So, if I ever do add this it will be easy to turn off or not on by default.

**Comment by pb-cdunn** [comment]
> On the topic of your final comment, did you read my message about maybe doing Mercurial/gdb/gnuplot-like acceptance of the shortest uniquely identifying prefix command/option/enum value? In this example, the command would have just executed if you had no other commands prefixed by "data".

I like the current way better. I'm not a fan of automating everything, but as a user I love to be informed of what I probably should have done. It saves time, and it feels empowering.

**Comment by c-blake** [comment]
Ok.  One vote for "off by default" if I ever add that.  Fair enough. :-)

**Comment by pb-cdunn** [comment]
Actually, accepting *truncated* sub-commands would be very useful, similar to truncated options.

**Comment by c-blake** [comment]
Hmm.  What did you think I meant by shortest uniquely identifying prefix if not truncation?  I think that means the same thing..Just one has more a "set of choices" perspective while the other is maybe more user-centered.

**Comment by pb-cdunn** [comment]
Oh, then yes. Up-vote!

**Comment by c-blake** [comment]
Ok.  This one's a bit more work, though. Normalizing a string for matching purposes requires the whole set of choices, not just the identifier itself..normalizing is sort of the "maximum truncation that preserves uniqueness".  So, internal stuff has to change to support it/make those choice sets available at matching time.  Not sure when/if I'll get around to it, but it's obv. quite off topic for this issue. :-)  You just mentioned liking the suggestion framework and this is a related idea.
